version: '3.8'

services:
  app:
    container_name: isellonline_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=myapps-isellonlinedb-diqya2
      - DB_PORT=3306
      - DB_DATABASE=ISellOnlineDB
      - DB_USERNAME=ISellOnlineDB
      - DB_PASSWORD=ISellOnlineDB
      - APP_URL=https://isellonline.website
    volumes:
      - ./storage:/var/www/html/storage
    restart: unless-stopped

volumes:
  mysql_data: